language: rust
rust:
    - stable
    - beta
    - nightly
os: linux
dist: bionic
sudo: require
jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - rustc
            - cargo

script:
    - cargo build
